version: '3.8'

services:
  vector:
    image: timberio/vector:0.42.0-alpine
    container_name: vector
    volumes:
      - ./agents/vector/vector.toml:/etc/vector/vector.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - opensearch
      - demo-app
    networks:
      - opensearch-net
