receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

exporters:
  # OpenSearch via Data Prepper
  otlp/opensearch:
    endpoint: data-prepper:21892
    tls:
      insecure: true

  # Oodle
  otlphttp/oodle:
    logs_endpoint: "https://${OODLE_INSTANCE}-logs.collector.oodle.ai/ingest/otel/v1/logs"
    headers:
      "X-OODLE-INSTANCE": "${OODLE_INSTANCE}"
      "X-API-KEY": "${OODLE_API_KEY}"

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/opensearch, otlphttp/oodle]
