receivers:
  tcplog:
    listen_address: "0.0.0.0:54525"
    operators:
      - type: json_parser
        parse_from: body

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

exporters:
  otlp:
    endpoint: data-prepper:21892
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [tcplog]
      processors: [batch]
      exporters: [otlp]
